import { Environment } from '../types';

export const arcticEnvironment: Environment = {
  id: 'arctic',
  name: 'Arctic',
  description: 'A serene winter wonderland with falling snow, ice crystals, and arctic wildlife',

  unlockRequirement: {
    fishCount: 60,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#B3E5FC', '#D4F1F9', '#E1F5FE'],
      positions: [0, 0.5, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'gradient',
      colors: ['#FFFFFF80', '#E0F7FA60'],
      positions: [0, 1],
      opacity: 0.6,
      parallaxFactor: 0.2,
      blendMode: 'screen',
    },
    {
      type: 'solid',
      colors: ['#81D4FA40'],
      opacity: 0.3,
      parallaxFactor: 0.15,
      blendMode: 'normal',
    },
  ],

  particles: [
    {
      type: 'snowflakes',
      density: 0.35,
      minSize: 3,
      maxSize: 8,
      minSpeed: 15,
      maxSpeed: 35,
      color: '#FFFFFF',
      opacity: 0.9,
      lifetime: 12000,
      acceleration: { x: 5, y: 20 },
      rotation: true,
      spawnRate: 4,
      maxCount: 40,
    },
    {
      type: 'ice-crystals',
      density: 0.12,
      minSize: 2,
      maxSize: 4,
      minSpeed: 5,
      maxSpeed: 15,
      color: '#81D4FA',
      opacity: 0.8,
      lifetime: 8000,
      acceleration: { x: 0, y: 0 },
      rotation: false,
      spawnRate: 1.5,
      maxCount: 15,
    },
    {
      type: 'penguins',
      density: 0.03,
      minSize: 15,
      maxSize: 25,
      minSpeed: 10,
      maxSpeed: 25,
      color: '#212121',
      opacity: 1.0,
      lifetime: 20000,
      acceleration: { x: 0, y: 5 },
      rotation: true,
      spawnRate: 0.2,
      maxCount: 3,
    },
    {
      type: 'seals',
      density: 0.02,
      minSize: 18,
      maxSize: 30,
      minSpeed: 15,
      maxSpeed: 35,
      color: '#757575',
      opacity: 0.95,
      lifetime: 18000,
      acceleration: { x: 0, y: 0 },
      rotation: true,
      spawnRate: 0.15,
      maxCount: 2,
    },
    {
      type: 'sparkles',
      density: 0.08,
      minSize: 1,
      maxSize: 3,
      minSpeed: 3,
      maxSpeed: 10,
      color: '#FFFFFF',
      opacity: 0.7,
      lifetime: 4000,
      rotation: false,
      spawnRate: 1,
      maxCount: 12,
    },
  ],

  physicsModifiers: [
    {
      type: 'windForce',
      strength: 0.35,
      direction: { x: 0.8, y: 0.1 },
      frequency: 0.5,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.35,
      noiseScale: 0.018,
      timeScale: 0.9,
    },
    {
      type: 'drift',
      strength: 0.2,
      direction: { x: 0.6, y: 0.1 },
      affectsFish: true,
      affectsParticles: true,
    },
  ],

  lighting: {
    ambient: 0.88,
    colorTemperature: 7500,
    shadows: true,
    shadowIntensity: 0.15,
  },

  timeOfDay: {
    hour: 11,
    sunPosition: { x: 0.4, y: 0.6 },
    ambientLight: 0.88,
    colorTemperature: 7500,
    shadowIntensity: 0.15,
  },

  audio: {
    ambient: 'arctic_ambient',
    volume: 0.3,
    loop: true,
  },

  colors: {
    primary: '#212121',
    secondary: '#FFFFFF',
    accent: '#81D4FA',
    text: '#212121',
    particle: '#FFFFFF',
  },

  fishBehavior: {
    speedMultiplier: 0.95,
    separationMultiplier: 1.05,
    alignmentMultiplier: 1.0,
    cohesionMultiplier: 1.0,
    maxForceMultiplier: 0.95,
  },

  performance: {
    maxParticles: 72,
    particleUpdateRate: 60,
    renderQuality: 'medium',
    enableShadows: true,
    enableReflections: true,
  },
};
