import { Environment } from '../types';

export const caveEnvironment: Environment = {
  id: 'cave',
  name: 'Cave',
  description: 'Dark underground cavern illuminated by glowing creatures and mysterious crystals',

  unlockRequirement: {
    fishCount: 80,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#1A1A1A', '#2C2C2C'],
      positions: [0, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'pattern',
      colors: ['#212121', '#1A1A1A', '#2C2C2C'],
      opacity: 0.7,
      parallaxFactor: 0.18,
      blendMode: 'multiply',
    },
    {
      type: 'gradient',
      colors: ['#00E5FF20', '#9C27B020'],
      positions: [0, 1],
      opacity: 0.2,
      parallaxFactor: 0.08,
      blendMode: 'screen',
    },
  ],

  particles: [
    {
      type: 'cave-bats',
      density: 0.3,
      minSize: 14,
      maxSize: 22,
      minSpeed: 60,
      maxSpeed: 110,
      color: '#212121',
      opacity: 0.9,
      lifetime: 5000,
      acceleration: { x: 40, y: -20 },
      rotation: false,
      spawnRate: 1.2,
      maxCount: 12,
    },
    {
      type: 'glowworms',
      density: 0.4,
      minSize: 3,
      maxSize: 5,
      minSpeed: 5,
      maxSpeed: 12,
      color: '#00E5FF',
      opacity: 0.95,
      lifetime: 0,
      rotation: false,
      spawnRate: 2.0,
      maxCount: 20,
    },
    {
      type: 'water-droplets',
      density: 0.35,
      minSize: 2,
      maxSize: 4,
      minSpeed: 80,
      maxSpeed: 150,
      color: '#81D4FA',
      opacity: 0.75,
      lifetime: 3000,
      acceleration: { x: 0, y: 300 },
      rotation: false,
      spawnRate: 2.5,
      maxCount: 15,
    },
    {
      type: 'cave-crickets',
      density: 0.2,
      minSize: 6,
      maxSize: 10,
      minSpeed: 30,
      maxSpeed: 70,
      color: '#6D4C41',
      opacity: 0.8,
      lifetime: 4000,
      acceleration: { x: 20, y: -100 },
      rotation: false,
      spawnRate: 0.8,
      maxCount: 8,
    },
    {
      type: 'crystals',
      density: 0.25,
      minSize: 12,
      maxSize: 20,
      minSpeed: 0,
      maxSpeed: 0,
      color: '#9C27B0',
      opacity: 0.9,
      lifetime: 0,
      rotation: false,
      spawnRate: 1.5,
      maxCount: 10,
    },
  ],

  physicsModifiers: [
    {
      type: 'drippingWater',
      strength: 0.3,
      direction: { x: 0, y: 1 },
      frequency: 0.4,
      affectsFish: false,
      affectsParticles: true,
      turbulence: 0.05,
      noiseScale: 0.003,
      timeScale: 0.6,
    },
    {
      type: 'drift',
      strength: 0.05,
      direction: { x: 0.1, y: 0 },
      affectsFish: true,
      affectsParticles: false,
    },
  ],

  lighting: {
    ambient: 0.25,
    colorTemperature: 7000,
    shadows: true,
    shadowIntensity: 0.8,
  },

  audio: {
    ambient: 'cave_ambient',
    volume: 0.4,
    loop: true,
  },

  colors: {
    primary: '#00E5FF',
    secondary: '#9C27B0',
    accent: '#81D4FA',
    text: '#FFFFFF',
    particle: '#00BCD4',
  },

  fishBehavior: {
    speedMultiplier: 0.8,
    separationMultiplier: 1.1,
    alignmentMultiplier: 1.0,
    cohesionMultiplier: 1.3,
    maxForceMultiplier: 0.85,
  },

  performance: {
    maxParticles: 65,
    particleUpdateRate: 60,
    renderQuality: 'medium',
    enableShadows: true,
    enableReflections: true,
  },
};
