import { Environment } from '../types';

export const coralReefEnvironment: Environment = {
  id: 'coral-reef',
  name: 'Coral Reef',
  description: 'A vibrant underwater ecosystem with colorful coral, schooling fish, and glowing plankton',

  unlockRequirement: {
    fishCount: 50,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#004D40', '#00695C', '#00796B'],
      positions: [0, 0.6, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'gradient',
      colors: ['#FF6E4080', '#E91E6360'],
      positions: [0, 1],
      opacity: 0.3,
      parallaxFactor: 0.15,
      blendMode: 'screen',
    },
    {
      type: 'gradient',
      colors: ['#2E7D3260', '#00695C80'],
      positions: [0, 1],
      opacity: 0.4,
      parallaxFactor: 0.25,
      blendMode: 'normal',
    },
  ],

  particles: [
    {
      type: 'bubbles',
      density: 0.35,
      minSize: 2,
      maxSize: 10,
      minSpeed: 25,
      maxSpeed: 60,
      color: '#FFFFFF',
      opacity: 0.5,
      lifetime: 4000,
      acceleration: { x: 0, y: -40 },
      spawnRate: 6,
      maxCount: 40,
    },
    {
      type: 'coral-fish',
      density: 0.25,
      minSize: 4,
      maxSize: 10,
      minSpeed: 30,
      maxSpeed: 70,
      color: '#00BCD4',
      opacity: 0.9,
      lifetime: 12000,
      acceleration: { x: 0, y: 0 },
      rotation: true,
      spawnRate: 3,
      maxCount: 30,
    },
    {
      type: 'plankton',
      density: 0.4,
      minSize: 1,
      maxSize: 2,
      minSpeed: 5,
      maxSpeed: 15,
      color: '#4CAF50',
      opacity: 0.7,
      lifetime: 20000,
      acceleration: { x: 0, y: 2 },
      rotation: false,
      spawnRate: 5,
      maxCount: 50,
    },
    {
      type: 'jellyfish',
      density: 0.05,
      minSize: 12,
      maxSize: 25,
      minSpeed: 10,
      maxSpeed: 25,
      color: '#9C27B0',
      opacity: 0.6,
      lifetime: 18000,
      acceleration: { x: 0, y: -5 },
      rotation: false,
      spawnRate: 0.4,
      maxCount: 5,
    },
    {
      type: 'sparkles',
      density: 0.15,
      minSize: 1,
      maxSize: 3,
      minSpeed: 8,
      maxSpeed: 20,
      color: '#FFC107',
      opacity: 0.8,
      lifetime: 3000,
      rotation: false,
      spawnRate: 2,
      maxCount: 25,
    },
  ],

  physicsModifiers: [
    {
      type: 'waterCurrent',
      strength: 0.4,
      direction: { x: 0.6, y: 0.2 },
      frequency: 0.6,
      scale: 0.004,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.25,
      noiseScale: 0.015,
      timeScale: 0.7,
    },
    {
      type: 'turbulence',
      strength: 0.2,
      frequency: 0.4,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.3,
      noiseScale: 0.02,
      timeScale: 0.5,
    },
    {
      type: 'drift',
      strength: 0.15,
      direction: { x: 0.4, y: -0.05 },
      affectsFish: true,
      affectsParticles: true,
    },
  ],

  lighting: {
    ambient: 0.75,
    colorTemperature: 7000,
    shadows: true,
    shadowIntensity: 0.5,
  },

  timeOfDay: {
    hour: 13,
    sunPosition: { x: 0.6, y: 0.7 },
    ambientLight: 0.75,
    colorTemperature: 7000,
    shadowIntensity: 0.5,
  },

  audio: {
    ambient: 'coral_reef_ambient',
    volume: 0.4,
    loop: true,
  },

  colors: {
    primary: '#00BCD4',
    secondary: '#FFC107',
    accent: '#FF6E40',
    text: '#FFFFFF',
    particle: '#4CAF50',
  },

  fishBehavior: {
    speedMultiplier: 1.15,
    separationMultiplier: 0.85,
    alignmentMultiplier: 1.2,
    cohesionMultiplier: 1.15,
    maxForceMultiplier: 1.1,
  },

  performance: {
    maxParticles: 150,
    particleUpdateRate: 60,
    renderQuality: 'high',
    enableShadows: true,
    enableReflections: true,
  },
};
