import { Environment } from '../types';

export const desertEnvironment: Environment = {
  id: 'desert',
  name: 'Desert',
  description: 'Arid sandy landscape with scorching sun and windswept dunes',

  unlockRequirement: {
    fishCount: 60,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#FFECB3', '#FFD54F'],
      positions: [0, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'pattern',
      colors: ['#FFE082', '#FFCA28', '#FFB300'],
      opacity: 0.6,
      parallaxFactor: 0.2,
      blendMode: 'overlay',
    },
    {
      type: 'gradient',
      colors: ['#FFD54F00', '#FFD54F40'],
      positions: [0, 1],
      opacity: 0.5,
      parallaxFactor: 0.1,
      blendMode: 'multiply',
    },
  ],

  particles: [
    {
      type: 'sand-grains',
      density: 0.8,
      minSize: 1,
      maxSize: 3,
      minSpeed: 80,
      maxSpeed: 150,
      color: '#D7CCC8',
      opacity: 0.6,
      lifetime: 4000,
      acceleration: { x: 100, y: 10 },
      rotation: false,
      spawnRate: 10,
      maxCount: 40,
    },
    {
      type: 'tumbleweeds',
      density: 0.08,
      minSize: 25,
      maxSize: 40,
      minSpeed: 30,
      maxSpeed: 60,
      color: '#8D6E63',
      opacity: 0.8,
      lifetime: 15000,
      acceleration: { x: 20, y: 2 },
      rotation: true,
      spawnRate: 0.2,
      maxCount: 3,
    },
    {
      type: 'vultures',
      density: 0.05,
      minSize: 18,
      maxSize: 28,
      minSpeed: 25,
      maxSpeed: 45,
      color: '#212121',
      opacity: 0.9,
      lifetime: 20000,
      acceleration: { x: 3, y: -2 },
      rotation: false,
      spawnRate: 0.1,
      maxCount: 2,
    },
    {
      type: 'scorpions',
      density: 0.15,
      minSize: 12,
      maxSize: 18,
      minSpeed: 15,
      maxSpeed: 35,
      color: '#6D4C41',
      opacity: 0.85,
      lifetime: 12000,
      acceleration: { x: 5, y: 0 },
      rotation: false,
      spawnRate: 0.4,
      maxCount: 5,
    },
    {
      type: 'lizards',
      density: 0.2,
      minSize: 10,
      maxSize: 16,
      minSpeed: 40,
      maxSpeed: 90,
      color: '#7CB342',
      opacity: 0.9,
      lifetime: 6000,
      acceleration: { x: 80, y: 0 },
      rotation: false,
      spawnRate: 0.6,
      maxCount: 6,
    },
  ],

  physicsModifiers: [
    {
      type: 'strongWind',
      strength: 0.4,
      direction: { x: 1, y: 0.1 },
      frequency: 0.8,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.3,
      noiseScale: 0.015,
      timeScale: 0.7,
    },
    {
      type: 'drift',
      strength: 0.25,
      direction: { x: 0.9, y: 0.05 },
      affectsFish: true,
      affectsParticles: true,
    },
  ],

  lighting: {
    ambient: 0.95,
    colorTemperature: 6000,
    shadows: true,
    shadowIntensity: 0.7,
  },

  audio: {
    ambient: 'desert_ambient',
    volume: 0.35,
    loop: true,
  },

  colors: {
    primary: '#FFD54F',
    secondary: '#7CB342',
    accent: '#D7CCC8',
    text: '#3E2723',
    particle: '#8D6E63',
  },

  fishBehavior: {
    speedMultiplier: 1.2,
    separationMultiplier: 1.3,
    alignmentMultiplier: 0.9,
    cohesionMultiplier: 0.8,
    maxForceMultiplier: 1.1,
  },

  performance: {
    maxParticles: 56,
    particleUpdateRate: 60,
    renderQuality: 'medium',
    enableShadows: true,
    enableReflections: false,
  },
};
