import { Environment } from '../types';

export const jungleEnvironment: Environment = {
  id: 'jungle',
  name: 'Jungle',
  description: 'Dense tropical rainforest alive with vibrant colors and exotic creatures',

  unlockRequirement: {
    fishCount: 50,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#1B5E20', '#2E7D32'],
      positions: [0, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'pattern',
      colors: ['#1B5E20', '#27632A', '#2E7D32'],
      opacity: 0.8,
      parallaxFactor: 0.15,
      blendMode: 'multiply',
    },
    {
      type: 'gradient',
      colors: ['#00000000', '#1B5E2060'],
      positions: [0, 0.8],
      opacity: 0.4,
      parallaxFactor: 0.05,
      blendMode: 'multiply',
    },
  ],

  particles: [
    {
      type: 'parrots',
      density: 0.15,
      minSize: 20,
      maxSize: 35,
      minSpeed: 40,
      maxSpeed: 80,
      color: '#F44336',
      opacity: 1,
      lifetime: 8000,
      acceleration: { x: 10, y: 5 },
      rotation: true,
      spawnRate: 0.5,
      maxCount: 5,
    },
    {
      type: 'tropical-butterflies',
      density: 0.5,
      minSize: 8,
      maxSize: 15,
      minSpeed: 20,
      maxSpeed: 40,
      color: '#FF6B35',
      opacity: 0.9,
      lifetime: 12000,
      acceleration: { x: 5, y: -3 },
      rotation: true,
      spawnRate: 1.5,
      maxCount: 15,
    },
    {
      type: 'fireflies',
      density: 0.3,
      minSize: 3,
      maxSize: 6,
      minSpeed: 10,
      maxSpeed: 25,
      color: '#FFEB3B',
      opacity: 0.85,
      lifetime: 6000,
      rotation: false,
      spawnRate: 1.2,
      maxCount: 12,
    },
    {
      type: 'rain-drops',
      density: 0.6,
      minSize: 2,
      maxSize: 4,
      minSpeed: 200,
      maxSpeed: 300,
      color: '#FFFFFF',
      opacity: 0.5,
      lifetime: 2000,
      acceleration: { x: 0, y: 400 },
      rotation: false,
      spawnRate: 8,
      maxCount: 30,
    },
    {
      type: 'leaves',
      density: 0.4,
      minSize: 8,
      maxSize: 14,
      minSpeed: 15,
      maxSpeed: 30,
      color: '#43A047',
      opacity: 0.7,
      lifetime: 10000,
      acceleration: { x: 3, y: 20 },
      rotation: true,
      spawnRate: 1.0,
      maxCount: 15,
    },
  ],

  physicsModifiers: [
    {
      type: 'humidAir',
      strength: 0.1,
      direction: { x: 0.2, y: 0.1 },
      frequency: 0.3,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.15,
      noiseScale: 0.008,
      timeScale: 0.4,
    },
    {
      type: 'drift',
      strength: 0.08,
      direction: { x: -0.1, y: 0.05 },
      affectsFish: true,
      affectsParticles: true,
    },
  ],

  lighting: {
    ambient: 0.7,
    colorTemperature: 5500,
    shadows: true,
    shadowIntensity: 0.5,
  },

  audio: {
    ambient: 'jungle_ambient',
    volume: 0.5,
    loop: true,
  },

  colors: {
    primary: '#F44336',
    secondary: '#FFEB3B',
    accent: '#FF6B35',
    text: '#FFFFFF',
    particle: '#43A047',
  },

  fishBehavior: {
    speedMultiplier: 0.9,
    separationMultiplier: 1.2,
    alignmentMultiplier: 1.1,
    cohesionMultiplier: 1.0,
    maxForceMultiplier: 0.95,
  },

  performance: {
    maxParticles: 77,
    particleUpdateRate: 60,
    renderQuality: 'high',
    enableShadows: true,
    enableReflections: false,
  },
};
