import { Environment } from '../types';

export const nightSkyEnvironment: Environment = {
  id: 'night-sky',
  name: 'Night Sky',
  description: 'A mysterious nocturnal environment with fireflies, moths, and shooting stars',

  unlockRequirement: {
    fishCount: 40,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#0A0E27', '#141936', '#1A1F3A'],
      positions: [0, 0.5, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'solid',
      colors: ['#FFFFFF'],
      opacity: 0.15,
      parallaxFactor: 0.05,
      blendMode: 'screen',
    },
    {
      type: 'solid',
      colors: ['#1A1F3A60'],
      opacity: 0.4,
      parallaxFactor: 0.1,
      blendMode: 'multiply',
    },
  ],

  particles: [
    {
      type: 'fireflies',
      density: 0.3,
      minSize: 2,
      maxSize: 5,
      minSpeed: 15,
      maxSpeed: 35,
      color: '#FFEB3B',
      opacity: 0.9,
      lifetime: 5000,
      acceleration: { x: 0, y: -10 },
      rotation: false,
      spawnRate: 4,
      maxCount: 35,
    },
    {
      type: 'moths',
      density: 0.15,
      minSize: 4,
      maxSize: 8,
      minSpeed: 20,
      maxSpeed: 45,
      color: '#EEEEEE',
      opacity: 0.7,
      lifetime: 8000,
      acceleration: { x: 0, y: 5 },
      rotation: true,
      spawnRate: 2,
      maxCount: 15,
    },
    {
      type: 'shooting-stars',
      density: 0.02,
      minSize: 2,
      maxSize: 4,
      minSpeed: 200,
      maxSpeed: 350,
      color: '#FFFFFF',
      opacity: 1.0,
      lifetime: 1500,
      acceleration: { x: 50, y: 100 },
      rotation: false,
      spawnRate: 0.3,
      maxCount: 3,
    },
    {
      type: 'bats',
      density: 0.08,
      minSize: 6,
      maxSize: 12,
      minSpeed: 60,
      maxSpeed: 100,
      color: '#212121',
      opacity: 0.85,
      lifetime: 6000,
      acceleration: { x: 0, y: 0 },
      rotation: false,
      spawnRate: 1,
      maxCount: 8,
    },
    {
      type: 'stars',
      density: 0.25,
      minSize: 1,
      maxSize: 2,
      minSpeed: 0,
      maxSpeed: 2,
      color: '#FFFFFF',
      opacity: 0.6,
      lifetime: 30000,
      acceleration: { x: 0, y: 0 },
      rotation: false,
      spawnRate: 0.5,
      maxCount: 30,
    },
  ],

  physicsModifiers: [
    {
      type: 'windForce',
      strength: 0.15,
      direction: { x: 0.5, y: 0.05 },
      frequency: 0.4,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.2,
      noiseScale: 0.012,
      timeScale: 0.6,
    },
    {
      type: 'drift',
      strength: 0.08,
      direction: { x: 0, y: -0.1 },
      affectsFish: false,
      affectsParticles: true,
    },
  ],

  lighting: {
    ambient: 0.35,
    colorTemperature: 4000,
    shadows: true,
    shadowIntensity: 0.7,
  },

  timeOfDay: {
    hour: 23,
    sunPosition: { x: 0.5, y: -0.3 },
    ambientLight: 0.35,
    colorTemperature: 4000,
    shadowIntensity: 0.7,
  },

  audio: {
    ambient: 'night_ambient',
    volume: 0.25,
    loop: true,
  },

  colors: {
    primary: '#FFEB3B',
    secondary: '#EEEEEE',
    accent: '#FFFFFF',
    text: '#FFFFFF',
    particle: '#FFEB3B',
  },

  fishBehavior: {
    speedMultiplier: 1.1,
    separationMultiplier: 0.9,
    alignmentMultiplier: 1.05,
    cohesionMultiplier: 0.95,
    maxForceMultiplier: 1.05,
  },

  performance: {
    maxParticles: 91,
    particleUpdateRate: 60,
    renderQuality: 'high',
    enableShadows: true,
    enableReflections: false,
  },
};
