import { Environment } from '../types';

export const savannaEnvironment: Environment = {
  id: 'savanna',
  name: 'Savanna',
  description: 'Expansive African grassland bathed in golden sunset with majestic wildlife',

  unlockRequirement: {
    fishCount: 90,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#FF9800', '#FFA726', '#FFB74D'],
      positions: [0, 0.5, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'pattern',
      colors: ['#FFB74D', '#FFA726', '#FF9800'],
      opacity: 0.5,
      parallaxFactor: 0.22,
      blendMode: 'overlay',
    },
    {
      type: 'gradient',
      colors: ['#FF980000', '#FF980050'],
      positions: [0, 1],
      opacity: 0.35,
      parallaxFactor: 0.12,
      blendMode: 'multiply',
    },
  ],

  particles: [
    {
      type: 'bats',
      density: 0.4,
      minSize: 8,
      maxSize: 14,
      minSpeed: 40,
      maxSpeed: 70,
      color: '#212121',
      opacity: 0.85,
      lifetime: 10000,
      acceleration: { x: 15, y: -5 },
      rotation: false,
      spawnRate: 1.5,
      maxCount: 15,
    },
    {
      type: 'sand',
      density: 0.6,
      minSize: 2,
      maxSize: 4,
      minSpeed: 30,
      maxSpeed: 60,
      color: '#D7CCC8',
      opacity: 0.5,
      lifetime: 6000,
      acceleration: { x: 40, y: 5 },
      rotation: false,
      spawnRate: 5,
      maxCount: 30,
    },
    {
      type: 'zebras',
      density: 0.05,
      minSize: 35,
      maxSize: 50,
      minSpeed: 20,
      maxSpeed: 40,
      color: '#000000',
      opacity: 0.95,
      lifetime: 25000,
      acceleration: { x: 5, y: 0 },
      rotation: false,
      spawnRate: 0.1,
      maxCount: 2,
    },
    {
      type: 'gazelles',
      density: 0.08,
      minSize: 28,
      maxSize: 40,
      minSpeed: 50,
      maxSpeed: 90,
      color: '#8D6E63',
      opacity: 0.9,
      lifetime: 8000,
      acceleration: { x: 60, y: -30 },
      rotation: false,
      spawnRate: 0.3,
      maxCount: 3,
    },
    {
      type: 'lions',
      density: 0.03,
      minSize: 40,
      maxSize: 55,
      minSpeed: 15,
      maxSpeed: 30,
      color: '#FF9800',
      opacity: 0.95,
      lifetime: 30000,
      acceleration: { x: 8, y: 0 },
      rotation: false,
      spawnRate: 0.05,
      maxCount: 1,
    },
    {
      type: 'tropical-butterflies',
      density: 0.3,
      minSize: 6,
      maxSize: 12,
      minSpeed: 25,
      maxSpeed: 45,
      color: '#FFEB3B',
      opacity: 0.85,
      lifetime: 12000,
      acceleration: { x: 8, y: -4 },
      rotation: true,
      spawnRate: 1.2,
      maxCount: 10,
    },
  ],

  physicsModifiers: [
    {
      type: 'savannaWind',
      strength: 0.25,
      direction: { x: 0.8, y: 0.05 },
      frequency: 0.6,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.2,
      noiseScale: 0.012,
      timeScale: 0.5,
    },
    {
      type: 'drift',
      strength: 0.18,
      direction: { x: 0.5, y: 0 },
      affectsFish: true,
      affectsParticles: true,
    },
  ],

  lighting: {
    ambient: 0.9,
    colorTemperature: 5000,
    shadows: true,
    shadowIntensity: 0.6,
  },

  audio: {
    ambient: 'savanna_ambient',
    volume: 0.45,
    loop: true,
  },

  colors: {
    primary: '#FF9800',
    secondary: '#FFB74D',
    accent: '#212121',
    text: '#3E2723',
    particle: '#D7CCC8',
  },

  fishBehavior: {
    speedMultiplier: 1.1,
    separationMultiplier: 1.2,
    alignmentMultiplier: 1.1,
    cohesionMultiplier: 0.9,
    maxForceMultiplier: 1.05,
  },

  performance: {
    maxParticles: 61,
    particleUpdateRate: 60,
    renderQuality: 'high',
    enableShadows: true,
    enableReflections: false,
  },
};
