import { Environment } from '../types';

export const spaceEnvironment: Environment = {
  id: 'space',
  name: 'Space',
  description: 'Cosmic outer space filled with mysterious alien creatures and celestial wonders',

  unlockRequirement: {
    fishCount: 75,
  },

  backgroundLayers: [
    {
      type: 'gradient',
      colors: ['#0D0221', '#1A0B2E'],
      positions: [0, 1],
      opacity: 1,
      parallaxFactor: 0,
    },
    {
      type: 'pattern',
      colors: ['#16213E', '#0F3460', '#1A0B2E'],
      opacity: 0.4,
      parallaxFactor: 0.25,
      blendMode: 'screen',
    },
    {
      type: 'gradient',
      colors: ['#E94560', '#533483', '#0F3460'],
      positions: [0, 0.5, 1],
      opacity: 0.15,
      parallaxFactor: 0.1,
      blendMode: 'screen',
    },
  ],

  particles: [
    {
      type: 'stars',
      density: 1.2,
      minSize: 1,
      maxSize: 3,
      minSpeed: 5,
      maxSpeed: 15,
      color: '#FFFFFF',
      opacity: 0.9,
      lifetime: 0,
      rotation: false,
      spawnRate: 15,
      maxCount: 80,
    },
    {
      type: 'comets',
      density: 0.08,
      minSize: 15,
      maxSize: 25,
      minSpeed: 100,
      maxSpeed: 200,
      color: '#4FC3F7',
      opacity: 0.95,
      lifetime: 3000,
      acceleration: { x: 50, y: 30 },
      rotation: false,
      spawnRate: 0.3,
      maxCount: 3,
    },
    {
      type: 'space-debris',
      density: 0.3,
      minSize: 8,
      maxSize: 16,
      minSpeed: 10,
      maxSpeed: 30,
      color: '#9E9E9E',
      opacity: 0.7,
      lifetime: 20000,
      acceleration: { x: 2, y: 1 },
      rotation: true,
      spawnRate: 0.8,
      maxCount: 15,
    },
    {
      type: 'alien-creatures',
      density: 0.2,
      minSize: 18,
      maxSize: 30,
      minSpeed: 15,
      maxSpeed: 35,
      color: '#00E676',
      opacity: 0.85,
      lifetime: 15000,
      acceleration: { x: 3, y: -5 },
      rotation: false,
      spawnRate: 0.5,
      maxCount: 8,
    },
    {
      type: 'energy-orbs',
      density: 0.25,
      minSize: 10,
      maxSize: 18,
      minSpeed: 20,
      maxSpeed: 40,
      color: '#FFD600',
      opacity: 0.9,
      lifetime: 10000,
      acceleration: { x: 5, y: 8 },
      rotation: false,
      spawnRate: 1.0,
      maxCount: 12,
    },
  ],

  physicsModifiers: [
    {
      type: 'zeroGravity',
      strength: 0.05,
      direction: { x: 0, y: 0 },
      frequency: 0.2,
      affectsFish: true,
      affectsParticles: true,
      turbulence: 0.1,
      noiseScale: 0.005,
      timeScale: 0.3,
    },
    {
      type: 'drift',
      strength: 0.03,
      direction: { x: 0.1, y: -0.05 },
      affectsFish: true,
      affectsParticles: true,
    },
  ],

  lighting: {
    ambient: 0.3,
    colorTemperature: 8000,
    shadows: false,
    shadowIntensity: 0,
  },

  audio: {
    ambient: 'space_ambient',
    volume: 0.3,
    loop: true,
  },

  colors: {
    primary: '#00E676',
    secondary: '#E91E63',
    accent: '#4FC3F7',
    text: '#FFFFFF',
    particle: '#FFD600',
  },

  fishBehavior: {
    speedMultiplier: 0.7,
    separationMultiplier: 0.8,
    alignmentMultiplier: 0.9,
    cohesionMultiplier: 1.2,
    maxForceMultiplier: 0.6,
  },

  performance: {
    maxParticles: 118,
    particleUpdateRate: 60,
    renderQuality: 'high',
    enableShadows: false,
    enableReflections: false,
  },
};
